backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img" # Media files will be stored in the repo under images
public_folder: "/img" # The src attribute for uploaded media will begin with /images

collections:
  - name: "experience"
    label: "Item"
    folder: "_posts"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "inner"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
 